# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nspec.proto\":\n\x14\x43reateAccountRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"O\n\x0eServerResponse\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\">\n\x0bSendRequest\x12\n\n\x02to\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"$\n\x0eReceiveRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"*\n\x14\x44\x65leteAccountRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\")\n\x07Message\x12\r\n\x05\x66rom_\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"P\n\x08Messages\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x19\n\x07message\x18\x03 \x03(\x0b\x32\x08.Message\"\x07\n\x05\x45mpty\"(\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1c\n\x05Users\x12\x13\n\x04user\x18\x01 \x03(\x0b\x32\x05.User2\xce\x02\n\rClientAccount\x12\x37\n\rCreateAccount\x12\x15.CreateAccountRequest\x1a\x0f.ServerResponse\x12\x1b\n\tListUsers\x12\x06.Empty\x1a\x06.Users\x12\'\n\x05Login\x12\r.LoginRequest\x1a\x0f.ServerResponse\x12%\n\x04Send\x12\x0c.SendRequest\x1a\x0f.ServerResponse\x12,\n\x0eReceiveMessage\x12\x0f.ReceiveRequest\x1a\t.Messages\x12\x37\n\rDeleteAccount\x12\x15.DeleteAccountRequest\x1a\x0f.ServerResponse\x12\x30\n\x06Logout\x12\x15.DeleteAccountRequest\x1a\x0f.ServerResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spec_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEACCOUNTREQUEST._serialized_start=14
  _CREATEACCOUNTREQUEST._serialized_end=72
  _SERVERRESPONSE._serialized_start=74
  _SERVERRESPONSE._serialized_end=153
  _LOGINREQUEST._serialized_start=155
  _LOGINREQUEST._serialized_end=205
  _SENDREQUEST._serialized_start=207
  _SENDREQUEST._serialized_end=269
  _RECEIVEREQUEST._serialized_start=271
  _RECEIVEREQUEST._serialized_end=307
  _DELETEACCOUNTREQUEST._serialized_start=309
  _DELETEACCOUNTREQUEST._serialized_end=351
  _MESSAGE._serialized_start=353
  _MESSAGE._serialized_end=394
  _MESSAGES._serialized_start=396
  _MESSAGES._serialized_end=476
  _EMPTY._serialized_start=478
  _EMPTY._serialized_end=485
  _USER._serialized_start=487
  _USER._serialized_end=527
  _USERS._serialized_start=529
  _USERS._serialized_end=557
  _CLIENTACCOUNT._serialized_start=560
  _CLIENTACCOUNT._serialized_end=894
# @@protoc_insertion_point(module_scope)
